### ISSUE TITLE
Week 1 - Containerized service is not available in this repository

### ISSUE THREAD

**Issue by seVladimirs** [SAP-samples/sap-community-code-challenge-cloud-native#9]
[Here](https://github.com/SAP-samples/sap-community-code-challenge-cloud-native/blob/51b679e594780a2ff3e21e6349413f4dc64ed2cd/Challenges.md?plain=1#L16) is mentioned that containerized service is available for this repo, but the link leads to 404

**Comment by KevinMuessig** [comment]
Hi @seVladimirs I forgot to make the package public, totally my fault. Please go and try again!
